"""Add file_hash and analysis_json to resume

Revision ID: f48f3a53001b
Revises: f36724ed44a2
Create Date: 2026-04-03 10:32:42.343101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f48f3a53001b'
down_revision: Union[str, None] = 'f36724ed44a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('file_hash', sa.String(), nullable=True))
    op.add_column('resumes', sa.Column('analysis_json', sa.Text(), nullable=True))
    op.create_index(op.f('ix_resumes_file_hash'), 'resumes', ['file_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resumes_file_hash'), table_name='resumes')
    op.drop_column('resumes', 'analysis_json')
    op.drop_column('resumes', 'file_hash')
    # ### end Alembic commands ###
